// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCow3dt5jjfcpUEXsizpeu_ssMnI1Jw6VE',
    appId: '1:109239175463:web:e0422d7798abeaa3814102',
    messagingSenderId: '109239175463',
    projectId: 'flutter-chat-app-792dc',
    authDomain: 'flutter-chat-app-792dc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-792dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Ta03Ug9gU-W9vjT7682w4IF0B-1Ex1s',
    appId: '1:109239175463:android:fc77eaae63272ba8814102',
    messagingSenderId: '109239175463',
    projectId: 'flutter-chat-app-792dc',
    storageBucket: 'flutter-chat-app-792dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXB9ik4uhhfuBQGfvp7fJspsLDLZLGBSw',
    appId: '1:109239175463:ios:6bbbd7bd6297f60e814102',
    messagingSenderId: '109239175463',
    projectId: 'flutter-chat-app-792dc',
    storageBucket: 'flutter-chat-app-792dc.appspot.com',
    iosClientId: '109239175463-pfhmvm0mps0s791altcv06c71m5v2k2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXB9ik4uhhfuBQGfvp7fJspsLDLZLGBSw',
    appId: '1:109239175463:ios:d18c1ece813e8e5b814102',
    messagingSenderId: '109239175463',
    projectId: 'flutter-chat-app-792dc',
    storageBucket: 'flutter-chat-app-792dc.appspot.com',
    iosClientId: '109239175463-pvh0apf4ju0mt68eaph2pntnh3irpngg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
